# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Control Plane Provider Talos"
github_repo = "talos-systems/cluster-api-control-plane-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.9"

pre_release = false

preface = """\
"""

[notes]

